apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: home-iot-secret
spec:
  type: kv-v2 # 시크릿 type 입력

  # mount path
  mount: internal # 마운트 할 Secret Engine name 입력

  # path of the secret
  path: api/home-iot # 시크릿을 생성할 때 설정한 secret name을 설정한다.

  # dest k8s secret
  destination:
    name: home-iot-secret # kubernetes secret으로 생성할 kubernetes secret name 입력
    create: true # kubernetes secret으로 생성여부

  # static secret refresh interval
  refreshAfter: 60s # vault secret과 kuberentes secret 동기화 시간 입력

  # Name of the CRD to authenticate to Vault
  vaultAuthRef: static-auth # 2번에서 생성한 VaultAuth name 입력
