kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.service.serviceName }}
spec:
  selector:
    app: home-iot
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.network.containerPort }}

