# apiVersion: secrets.hashicorp.com/v1beta1
# kind: VaultAuth
# metadata:
#   name: static-auth
#   namespace: default
# spec:
#   kubernetes:
#     audiences:
#     - vault
#     role: admin
#     serviceAccount: vault
#     tokenExpirationSeconds: 600
#   method: kubernetes
#   mount: kubernetes

apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  namespace: default
  name: vault-connection
spec:
  # address to the Vault server.
  address: http://vault.vault.svc.cluster.local:8200
  skipTLSVerify: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vault-auth
spec:
  vaultConnectionRef: vault-connection
  method: kubernetes
  mount: vso
  kubernetes:
    role: vso-role
    serviceAccount: home-iot
