image:
  repository: ghcr.io/dispiny/home-iot
  tag: v1.0.2

labels:
  app:

service:
  serviceName: home-iot-svc

network:
  containerPort: 5000
  servicePort: 80
  serviceProtocol: TCP
  hostDNS: api.dispiny.life

replicas: 2
